services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: microtodo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080